$kind: environment
id: local
name: Local
values:
  - key: baseUrl
    value: https://jsonplaceholder.typicode.com
    type: default
  - key: timeout
    value: '30000'
    type: default
  - key: delay
    value: '0'
    type: default
