name: Production
values:
  - key: baseUrl
    value: https://jsonplaceholder.typicode.com
    type: default
  - key: timeout
    value: "60000"
    type: default
  - key: delay
    value: "200"
    type: default
color: 0
