name: Staging
values:
  - key: baseUrl
    value: https://jsonplaceholder.typicode.com
    type: default
  - key: timeout
    value: "30000"
    type: default
  - key: delay
    value: "100"
    type: default
color: 0
